"""empty message

Revision ID: 02ae1a8699c6
Revises: b94b6a0a3aeb
Create Date: 2023-09-27 13:46:40.525049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02ae1a8699c6'
down_revision = 'b94b6a0a3aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_entry', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('agenda_entry', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('agenda_entry', sa.Column('deviating_start_time', sa.DateTime(), nullable=True))
    op.add_column('agenda_entry', sa.Column('deviating_end_time', sa.DateTime(), nullable=True))
    op.add_column('agenda_entry', sa.Column('deviating_start_time_unknown', sa.Boolean(), server_default='false', nullable=True))
    op.drop_column('agenda_entry', 'deviating_time_unknown')
    op.drop_column('agenda_entry', 'time')
    op.drop_column('agenda_entry', 'deviating_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_entry', sa.Column('deviating_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('agenda_entry', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('agenda_entry', sa.Column('deviating_time_unknown', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('agenda_entry', 'deviating_start_time_unknown')
    op.drop_column('agenda_entry', 'deviating_end_time')
    op.drop_column('agenda_entry', 'deviating_start_time')
    op.drop_column('agenda_entry', 'end_time')
    op.drop_column('agenda_entry', 'start_time')
    # ### end Alembic commands ###
