"""Add GDPR consent table

Revision ID: 04aeca7278ec
Revises: 9a8bb21294a3
Create Date: 2023-01-11 14:01:16.055717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04aeca7278ec'
down_revision = '9a8bb21294a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consent',
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('consent_type', sa.Enum('event_notification', name='consenttype'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name=op.f('fk_user_consent_user_uuid_user')),
    sa.PrimaryKeyConstraint('user_uuid', 'consent_type', name=op.f('pk_user_consent'))
    )
    op.drop_constraint('_user_positionmapping_uic', 'user_positions', type_='unique')
    op.create_unique_constraint('_user_positionmapping_uic', 'user_positions', ['position_uuid', 'user_uuid', 'event_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_positionmapping_uic', 'user_positions', type_='unique')
    op.create_unique_constraint('_user_positionmapping_uic', 'user_positions', ['position_uuid', 'user_uuid'])
    op.drop_table('user_consent')
    # ### end Alembic commands ###
