"""Remove username field

Revision ID: 071b0c88773a
Revises: e13ccd2645b3
Create Date: 2026-09-22 14:11:31.808264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071b0c88773a'
down_revision = 'e13ccd2645b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_membership_personalia_user_uuid'), 'membership_personalia', ['user_uuid'])
    op.drop_constraint(op.f('uq_user_username'), 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_user_username'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_membership_personalia_user_uuid'), 'membership_personalia', type_='unique')
    # ### end Alembic commands ###
