"""ticket totp

Revision ID: 09fab2ff4d15
Revises: 4c3c6923b650
Create Date: 2026-03-10 14:43:20.614644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fab2ff4d15'
down_revision = '4c3c6923b650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_totp',
    sa.Column('ticket_uuid', sa.Integer(), nullable=False),
    sa.Column('totp', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_uuid'], ['ticket.ticket_id'], name=op.f('fk_ticket_totp_ticket_uuid_ticket')),
    sa.PrimaryKeyConstraint('ticket_uuid', name=op.f('pk_ticket_totp'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_totp')
    # ### end Alembic commands ###
