"""Tickets are now able to be checked in

Revision ID: 0cb24597d9c2
Revises: d5d4e0ac460b
Create Date: 2022-10-01 10:48:08.653351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb24597d9c2'
down_revision = 'd5d4e0ac460b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('checked_in', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'checked_in')
    # ### end Alembic commands ###
