"""Multitenant test

Revision ID: 0eee850a7ace
Revises: b648caf8d8fb
Create Date: 2025-08-25 18:04:28.925486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eee850a7ace'
down_revision = 'b648caf8d8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_type',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_event_type')),
    sa.UniqueConstraint('uuid', name=op.f('uq_event_type_uuid'))
    )
    op.add_column('crew', sa.Column('event_type', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_crew_event_type_event_type'), 'crew', 'event_type', ['event_type'], ['uuid'])
    op.add_column('event', sa.Column('event_type_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_event_event_type_uuid_event_type'), 'event', 'event_type', ['event_type_uuid'], ['uuid'])
    op.add_column('location', sa.Column('event_type_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_location_event_type_uuid_event_type'), 'location', 'event_type', ['event_type_uuid'], ['uuid'])
    op.add_column('position', sa.Column('event_type_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_position_event_type_uuid_event_type'), 'position', 'event_type', ['event_type_uuid'], ['uuid'])
    op.add_column('seatmap', sa.Column('event_type_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_seatmap_event_type_uuid_event_type'), 'seatmap', 'event_type', ['event_type_uuid'], ['uuid'])
    op.add_column('seatmap_background', sa.Column('event_type_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_seatmap_background_event_type_uuid_event_type'), 'seatmap_background', 'event_type', ['event_type_uuid'], ['uuid'])
    op.add_column('ticket_type', sa.Column('event_type_uuid', sa.UUID(), nullable=True))
    op.add_column('ticket_type', sa.Column('can_checkin', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(op.f('fk_ticket_type_event_type_uuid_event_type'), 'ticket_type', 'event_type', ['event_type_uuid'], ['uuid'])
    op.add_column('user_positions', sa.Column('event_type_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_user_positions_event_type_uuid_event_type'), 'user_positions', 'event_type', ['event_type_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_positions_event_type_uuid_event_type'), 'user_positions', type_='foreignkey')
    op.drop_column('user_positions', 'event_type_uuid')
    op.drop_constraint(op.f('fk_ticket_type_event_type_uuid_event_type'), 'ticket_type', type_='foreignkey')
    op.drop_column('ticket_type', 'can_checkin')
    op.drop_column('ticket_type', 'event_type_uuid')
    op.drop_constraint(op.f('fk_seatmap_background_event_type_uuid_event_type'), 'seatmap_background', type_='foreignkey')
    op.drop_column('seatmap_background', 'event_type_uuid')
    op.drop_constraint(op.f('fk_seatmap_event_type_uuid_event_type'), 'seatmap', type_='foreignkey')
    op.drop_column('seatmap', 'event_type_uuid')
    op.drop_constraint(op.f('fk_position_event_type_uuid_event_type'), 'position', type_='foreignkey')
    op.drop_column('position', 'event_type_uuid')
    op.drop_constraint(op.f('fk_location_event_type_uuid_event_type'), 'location', type_='foreignkey')
    op.drop_column('location', 'event_type_uuid')
    op.drop_constraint(op.f('fk_event_event_type_uuid_event_type'), 'event', type_='foreignkey')
    op.drop_column('event', 'event_type_uuid')
    op.drop_constraint(op.f('fk_crew_event_type_event_type'), 'crew', type_='foreignkey')
    op.drop_column('crew', 'event_type')
    op.drop_table('event_type')
    # ### end Alembic commands ###
