"""Add consent withdrawal code

Revision ID: 1bc50fd4843e
Revises: 2d7a36f1a5a5
Create Date: 2023-08-19 08:14:23.812838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc50fd4843e'
down_revision = '2d7a36f1a5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_withdrawal_code',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.Enum('event_notification', name='consenttype'), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name=op.f('fk_consent_withdrawal_code_user_uuid_user')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_consent_withdrawal_code')),
    sa.UniqueConstraint('uuid', name=op.f('uq_consent_withdrawal_code_uuid'))
    )
    op.create_unique_constraint(op.f('uq_ticket_voucher_uuid'), 'ticket_voucher', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ticket_voucher_uuid'), 'ticket_voucher', type_='unique')
    op.drop_table('consent_withdrawal_code')
    # ### end Alembic commands ###
