"""Events have an optional location

Revision ID: 1d65088f1aae
Revises: 428c56eeef7b
Create Date: 2022-08-11 16:06:51.239819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1d65088f1aae'
down_revision = '428c56eeef7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_location')),
    sa.UniqueConstraint('uuid', name=op.f('uq_location_uuid'))
    )
    op.add_column('event', sa.Column('location_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_event_location_uuid_location'), 'event', 'location', ['location_uuid'], ['uuid'])
    op.alter_column('password_reset_code', 'client_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('password_reset_code', 'client_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('fk_event_location_uuid_location'), 'event', type_='foreignkey')
    op.drop_column('event', 'location_uuid')
    op.drop_table('location')
    # ### end Alembic commands ###
