"""Added friendship feature

Revision ID: 21cbd812c638
Revises: c2fb90349bde
Create Date: 2023-09-08 12:44:16.499491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cbd812c638'
down_revision = 'c2fb90349bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('source_user_uuid', sa.UUID(), nullable=False),
    sa.Column('recipient_user_uuid', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('accepted', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_uuid'], ['user.uuid'], name=op.f('fk_friendship_recipient_user_uuid_user')),
    sa.ForeignKeyConstraint(['source_user_uuid'], ['user.uuid'], name=op.f('fk_friendship_source_user_uuid_user')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_friendship')),
    sa.UniqueConstraint('uuid', name=op.f('uq_friendship_uuid'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    # ### end Alembic commands ###
