"""Add application prompt to crew

Revision ID: 22f3a9c508e7
Revises: 42c094de65ac
Create Date: 2022-09-08 12:54:44.609034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f3a9c508e7'
down_revision = '42c094de65ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew', sa.Column('application_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew', 'application_prompt')
    # ### end Alembic commands ###
