"""Ticket transfer object

Revision ID: 29d94a752ab2
Revises: 8cad5b097f8b
Create Date: 2022-08-25 13:50:32.129138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29d94a752ab2'
down_revision = '8cad5b097f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_transfer',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('from_user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('to_user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ticket_uuid', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user_uuid'], ['user.uuid'], name=op.f('fk_ticket_transfer_from_user_uuid_user')),
    sa.ForeignKeyConstraint(['ticket_uuid'], ['ticket.ticket_id'], name=op.f('fk_ticket_transfer_ticket_uuid_ticket')),
    sa.ForeignKeyConstraint(['to_user_uuid'], ['user.uuid'], name=op.f('fk_ticket_transfer_to_user_uuid_user')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_ticket_transfer')),
    sa.UniqueConstraint('uuid', name=op.f('uq_ticket_transfer_uuid'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_transfer')
    # ### end Alembic commands ###
