"""Add ticket voucher

Revision ID: 2d7a36f1a5a5
Revises: 04aeca7278ec
Create Date: 2023-07-23 14:35:12.229168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d7a36f1a5a5'
down_revision = '04aeca7278ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_voucher',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('recipient_user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ticket_type_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('last_use_event_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('used', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_use_event_uuid'], ['event.uuid'], name=op.f('fk_ticket_voucher_last_use_event_uuid_event')),
    sa.ForeignKeyConstraint(['recipient_user_uuid'], ['user.uuid'], name=op.f('fk_ticket_voucher_recipient_user_uuid_user')),
    sa.ForeignKeyConstraint(['source_user_uuid'], ['user.uuid'], name=op.f('fk_ticket_voucher_source_user_uuid_user')),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], name=op.f('fk_ticket_voucher_ticket_id_ticket')),
    sa.ForeignKeyConstraint(['ticket_type_uuid'], ['ticket_type.uuid'], name=op.f('fk_ticket_voucher_ticket_type_uuid_ticket_type')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_ticket_voucher')),
    sa.UniqueConstraint('uuid', name=op.f('uq_ticket_voucher_uuid'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_voucher')
    # ### end Alembic commands ###
