"""card order

Revision ID: 358486e14fb6
Revises: b94b6a0a3aeb
Create Date: 2023-10-16 12:34:32.576402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '358486e14fb6'
down_revision = 'ae6348f3ed63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_order',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('event_uuid', sa.UUID(), nullable=False),
    sa.Column('subject_user_uuid', sa.UUID(), nullable=False),
    sa.Column('creator_user_uuid', sa.UUID(), nullable=False),
    sa.Column('updated_by_user_uuid', sa.UUID(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('state', postgresql.ENUM('CREATED', 'IN_PROGRESS', 'FINISHED', 'CANCELLED', name='orderstates'), server_default='CREATED', nullable=False),
    sa.ForeignKeyConstraint(['creator_user_uuid'], ['user.uuid'], name=op.f('fk_card_order_creator_user_uuid_user')),
    sa.ForeignKeyConstraint(['event_uuid'], ['event.uuid'], name=op.f('fk_card_order_event_uuid_event')),
    sa.ForeignKeyConstraint(['subject_user_uuid'], ['user.uuid'], name=op.f('fk_card_order_subject_user_uuid_user')),
    sa.ForeignKeyConstraint(['updated_by_user_uuid'], ['user.uuid'], name=op.f('fk_card_order_updated_by_user_uuid_user')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_card_order')),
    sa.UniqueConstraint('uuid', name=op.f('uq_card_order_uuid'))
    )
    op.alter_column('agenda_entry', 'created_by_user_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agenda_entry', 'created_by_user_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_table('card_order')
    # ### end Alembic commands ###
