"""Ticket type may have disclaimer

Revision ID: 39b4032d3686
Revises: 49c6ce337182
Create Date: 2026-09-28 14:31:46.159536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b4032d3686'
down_revision = '49c6ce337182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_type', sa.Column('disclaimer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_type', 'disclaimer')
    # ### end Alembic commands ###
