"""Store payment ID

Revision ID: 42c094de65ac
Revises: eeb47a836ce0
Create Date: 2022-08-29 14:09:16.072368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c094de65ac'
down_revision = 'eeb47a836ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_payment', sa.Column('payment_id', sa.Text(), nullable=False))
    op.drop_column('stripe_payment', 'client_secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_payment', sa.Column('client_secret', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('stripe_payment', 'payment_id')
    # ### end Alembic commands ###
