"""multitenant test 2

Revision ID: 45b6be09b41d
Revises: b648caf8d8fb
Create Date: 2025-09-20 09:06:00.040599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b6be09b41d'
down_revision = 'b648caf8d8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_brand',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_event_brand')),
    sa.UniqueConstraint('uuid', name=op.f('uq_event_brand_uuid'))
    )
    op.add_column('crew', sa.Column('event_brand', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_crew_event_brand_event_brand'), 'crew', 'event_brand', ['event_brand'], ['uuid'])
    op.add_column('event', sa.Column('event_brand_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_event_event_brand_uuid_event_brand'), 'event', 'event_brand', ['event_brand_uuid'], ['uuid'])
    op.add_column('location', sa.Column('event_brand_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_location_event_brand_uuid_event_brand'), 'location', 'event_brand', ['event_brand_uuid'], ['uuid'])
    op.add_column('position', sa.Column('event_brand_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_position_event_brand_uuid_event_brand'), 'position', 'event_brand', ['event_brand_uuid'], ['uuid'])
    op.add_column('seatmap', sa.Column('event_brand_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_seatmap_event_brand_uuid_event_brand'), 'seatmap', 'event_brand', ['event_brand_uuid'], ['uuid'])
    op.add_column('seatmap_background', sa.Column('event_brand_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_seatmap_background_event_brand_uuid_event_brand'), 'seatmap_background', 'event_brand', ['event_brand_uuid'], ['uuid'])
    op.add_column('ticket_type', sa.Column('event_brand_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_ticket_type_event_brand_uuid_event_brand'), 'ticket_type', 'event_brand', ['event_brand_uuid'], ['uuid'])
    op.add_column('user_positions', sa.Column('event_brand_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_user_positions_event_brand_uuid_event_brand'), 'user_positions', 'event_brand', ['event_brand_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_positions_event_brand_uuid_event_brand'), 'user_positions', type_='foreignkey')
    op.drop_column('user_positions', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_ticket_type_event_brand_uuid_event_brand'), 'ticket_type', type_='foreignkey')
    op.drop_column('ticket_type', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_seatmap_background_event_brand_uuid_event_brand'), 'seatmap_background', type_='foreignkey')
    op.drop_column('seatmap_background', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_seatmap_event_brand_uuid_event_brand'), 'seatmap', type_='foreignkey')
    op.drop_column('seatmap', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_position_event_brand_uuid_event_brand'), 'position', type_='foreignkey')
    op.drop_column('position', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_location_event_brand_uuid_event_brand'), 'location', type_='foreignkey')
    op.drop_column('location', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_event_event_brand_uuid_event_brand'), 'event', type_='foreignkey')
    op.drop_column('event', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_crew_event_brand_event_brand'), 'crew', type_='foreignkey')
    op.drop_column('crew', 'event_brand')
    op.drop_table('event_brand')
    # ### end Alembic commands ###
