"""ticket totp

Revision ID: 49cebe88616e
Revises: 4c3c6923b650
Create Date: 2026-03-10 17:02:09.585838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49cebe88616e'
down_revision = '4c3c6923b650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_totp',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('totp', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], name=op.f('fk_ticket_totp_ticket_id_ticket')),
    sa.PrimaryKeyConstraint('ticket_id', name=op.f('pk_ticket_totp'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_totp')
    # ### end Alembic commands ###
