"""Event announced boolean

Revision ID: 4b2fd2e9ba9b
Revises: 1b7888972f1d
Create Date: 2026-09-27 05:25:55.536929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2fd2e9ba9b'
down_revision = '1b7888972f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('announced', sa.Boolean(), server_default='true', nullable=False))
    op.create_unique_constraint(op.f('uq_event_ticket_type_mapping_uuid'), 'event_ticket_type_mapping', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_event_ticket_type_mapping_uuid'), 'event_ticket_type_mapping', type_='unique')
    op.drop_column('event', 'announced')
    # ### end Alembic commands ###
