"""grants admission

Revision ID: 4c3c6923b650
Revises: b648caf8d8fb
Create Date: 2026-03-01 12:05:04.967120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3c6923b650'
down_revision = 'b648caf8d8fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_type', sa.Column('grants_admission', sa.Boolean(), server_default='true', nullable=False))
    op.execute("update ticket_type set grants_admission='true' where seatable='true';")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_type', 'grants_admission')
    # ### end Alembic commands ###
