"""Add new transferable field

Revision ID: 52986905717f
Revises: 071b0c88773a
Create Date: 2026-09-23 17:05:53.028569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52986905717f'
down_revision = '071b0c88773a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_type', sa.Column('transferable', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_type', 'transferable')
    # ### end Alembic commands ###
