"""Add consent reversal code

Revision ID: 5f9f040772ab
Revises: 2d7a36f1a5a5
Create Date: 2023-08-18 17:58:12.750974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9f040772ab'
down_revision = '2d7a36f1a5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_reversal_code',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('consent_type', sa.Enum('event_notification', name='consenttype'), nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name=op.f('fk_consent_reversal_code_user_uuid_user')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_consent_reversal_code'))
    )
    op.create_unique_constraint(op.f('uq_ticket_voucher_uuid'), 'ticket_voucher', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ticket_voucher_uuid'), 'ticket_voucher', type_='unique')
    op.drop_table('consent_reversal_code')
    # ### end Alembic commands ###
