"""Fix lack of event_uuid in position mapping uniqueness constraint

Revision ID: 60fce51123b5
Revises: 9a8bb21294a3
Create Date: 2023-01-08 11:56:14.633451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60fce51123b5'
down_revision = '9a8bb21294a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_positionmapping_uic', 'user_positions', type_='unique')
    op.create_unique_constraint('_user_positionmapping_uic', 'user_positions', ['position_uuid', 'user_uuid', 'event_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_positionmapping_uic', 'user_positions', type_='unique')
    op.create_unique_constraint('_user_positionmapping_uic', 'user_positions', ['position_uuid', 'user_uuid'])
    # ### end Alembic commands ###
