"""Position mapping

Revision ID: 66f31c1d0613
Revises: 0cb24597d9c2
Create Date: 2022-11-24 13:40:28.495164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66f31c1d0613'
down_revision = '0951a436562c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_positions', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.execute('UPDATE user_positions set uuid=gen_random_uuid()');
    op.alter_column('user_positions', 'uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.add_column('user_positions', sa.Column('event_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('user_positions', sa.Column('created', sa.DateTime(), nullable=True))
    op.execute('UPDATE user_positions set created=NOW();')
    op.alter_column('user_positions', 'created',
               existing_type=sa.DateTime(),
               nullable=False)
    op.alter_column('user_positions', 'position_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('user_positions', 'user_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_user_positions_uuid'), 'user_positions', ['uuid'])
    op.create_foreign_key(op.f('fk_user_positions_event_uuid_event'), 'user_positions', 'event', ['event_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_positions_event_uuid_event'), 'user_positions', type_='foreignkey')
    op.drop_constraint(op.f('uq_user_positions_uuid'), 'user_positions', type_='unique')
    op.alter_column('user_positions', 'user_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('user_positions', 'position_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('user_positions', 'created')
    op.drop_column('user_positions', 'event_uuid')
    op.drop_column('user_positions', 'uuid')
    # ### end Alembic commands ###
