"""Add discord mapping tables

Revision ID: 973632b0d6e9
Revises: 0cb24597d9c2
Create Date: 2022-12-28 18:22:45.242007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '973632b0d6e9'
down_revision = '0cb24597d9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_mapping',
    sa.Column('discord_id', sa.Text(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('discord_refresh_token', sa.Text(), nullable=False),
    sa.Column('discord_access_token', sa.Text(), nullable=False),
    sa.Column('discord_access_token_expiry', sa.DateTime(), nullable=False),
    sa.Column('discord_username', sa.Text(), nullable=False),
    sa.Column('discord_username_last_check', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name=op.f('fk_discord_mapping_user_uuid_user')),
    sa.PrimaryKeyConstraint('discord_id', 'user_uuid', name=op.f('pk_discord_mapping'))
    )
    op.create_table('discord_mapping_oauth_state',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name=op.f('fk_discord_mapping_oauth_state_user_uuid_user')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_discord_mapping_oauth_state')),
    sa.UniqueConstraint('code', name=op.f('uq_discord_mapping_oauth_state_code'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_mapping_oauth_state')
    op.drop_table('discord_mapping')
    # ### end Alembic commands ###
