"""Payments are connected to an event

Revision ID: a40ec93ac7aa
Revises: 1d65088f1aae
Create Date: 2022-08-19 16:18:50.875305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a40ec93ac7aa'
down_revision = '1d65088f1aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_location_uuid'), 'location', ['uuid'])
    op.add_column('payment', sa.Column('event_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(op.f('fk_payment_event_uuid_event'), 'payment', 'event', ['event_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_payment_event_uuid_event'), 'payment', type_='foreignkey')
    op.drop_column('payment', 'event_uuid')
    op.drop_constraint(op.f('uq_location_uuid'), 'location', type_='unique')
    # ### end Alembic commands ###
