"""empty message

Revision ID: ae6348f3ed63
Revises: b94b6a0a3aeb
Create Date: 2024-03-10 15:05:50.706126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6348f3ed63'
down_revision = 'b94b6a0a3aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agenda_entry', sa.Column('duration', sa.Integer(), nullable=True))
    op.alter_column('agenda_entry', 'created_by_user_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agenda_entry', 'created_by_user_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('agenda_entry', 'duration')
    # ### end Alembic commands ###
