"""Add membership information to ticket

Revision ID: d5d4e0ac460b
Revises: 22f3a9c508e7
Create Date: 2022-09-17 06:06:46.539220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d4e0ac460b'
down_revision = '22f3a9c508e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_type', sa.Column('requires_membership', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('ticket_type', sa.Column('grants_membership', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_type', 'grants_membership')
    op.drop_column('ticket_type', 'requires_membership')
    # ### end Alembic commands ###
