"""MembershipPersonalia

Revision ID: e13ccd2645b3
Revises: ff2244b4bdc4
Create Date: 2026-09-22 10:50:36.693076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13ccd2645b3'
down_revision = 'ff2244b4bdc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_personalia',
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.Text(), nullable=False),
    sa.Column('country_code', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], name=op.f('fk_membership_personalia_user_uuid_user')),
    sa.PrimaryKeyConstraint('user_uuid', name=op.f('pk_membership_personalia')),
    sa.UniqueConstraint('user_uuid', name=op.f('uq_membership_personalia_user_uuid'))
    )
    
    op.get_bind().execute(sa.text('INSERT INTO membership_personalia (user_uuid, address, phone, postal_code, country_code, created, modified) (SELECT uuid, address, phone, postal_code, country_code, NOW(), NOW() from "user");'))

    op.drop_column('user', 'address')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'country_code')
    op.drop_column('user', 'postal_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('postal_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('country_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_table('membership_personalia')
    # ### end Alembic commands ###
