"""Ticket transfer can be reverted

Revision ID: eeb47a836ce0
Revises: 29d94a752ab2
Create Date: 2022-08-25 16:29:47.424454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb47a836ce0'
down_revision = '29d94a752ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_transfer', sa.Column('reverted', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint(op.f('uq_ticket_transfer_uuid'), 'ticket_transfer', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ticket_transfer_uuid'), 'ticket_transfer', type_='unique')
    op.drop_column('ticket_transfer', 'reverted')
    # ### end Alembic commands ###
