"""Multitenancy

Revision ID: ff2244b4bdc4
Revises: b648caf8d8fb
Create Date: 2026-08-31 15:32:06.822486

"""
from alembic import op
import sqlalchemy as sa

import uuid


# revision identifiers, used by Alembic.
revision = 'ff2244b4bdc4'
down_revision = 'b648caf8d8fb'
branch_labels = None
depends_on = None

# Every table that gains an event_brand_uuid. Existing rows are all placed on
# the default brand created below.
BRAND_TABLES = [
    'crew',
    'event',
    'location',
    'position',
    'seatmap',
    'seatmap_background',
    'ticket_type',
    'ticket_voucher',
]

# position keeps a nullable brand: a position without a brand grants global
# permissions rather than brand scoped ones, see views/user/oauth.py. It is
# therefore also backfilled separately, and left alone where it is global.
NOT_NULL_BRAND_TABLES = [table for table in BRAND_TABLES if table != 'position']
BACKFILL_BRAND_TABLES = NOT_NULL_BRAND_TABLES


def upgrade():
    default_brand_uuid = uuid.uuid4()

    event_brand_table = op.create_table('event_brand',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_event_brand')),
    sa.UniqueConstraint('uuid', name=op.f('uq_event_brand_uuid'))
    )

    op.bulk_insert(event_brand_table,
        [
            {
                'uuid': default_brand_uuid,
                'name': 'Default brand',
            },
        ]
    )

    # Postgres discards a UNIQUE that duplicates the primary key when it is
    # inlined in CREATE TABLE, so add it separately like the older migrations do
    op.create_unique_constraint(op.f('uq_event_brand_uuid'), 'event_brand', ['uuid'])

    # Nullable first, so we can add the column to tables that already have rows
    for table in BRAND_TABLES:
        op.add_column(table, sa.Column('event_brand_uuid', sa.UUID(), nullable=True))
        op.create_foreign_key(op.f(f'fk_{table}_event_brand_uuid_event_brand'), table, 'event_brand', ['event_brand_uuid'], ['uuid'])

    # Everything that existed before multitenancy belongs to the default brand
    for table in BACKFILL_BRAND_TABLES:
        op.execute(
            sa.text(f'UPDATE "{table}" SET event_brand_uuid = :brand')
              .bindparams(brand=str(default_brand_uuid))
        )

    # A position is only given the default brand if a crew or a team ties it to
    # one. Positions without either are global, and stay global.
    op.execute(
        sa.text("""
            UPDATE "position" SET event_brand_uuid = :brand
            WHERE crew_uuid IS NOT NULL OR team_uuid IS NOT NULL
        """).bindparams(brand=str(default_brand_uuid))
    )

    for table in NOT_NULL_BRAND_TABLES:
        op.alter_column(table, 'event_brand_uuid', existing_type=sa.UUID(), nullable=False)

    op.add_column('store_session', sa.Column('event_uuid', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_store_session_event_uuid_event'), 'store_session', 'event', ['event_uuid'], ['uuid'])

    # Assign every old store session to the event that was current when it was
    # created - the first event that had not ended yet, the same rule
    # get_current_event uses. Sessions created after every known event ended
    # fall back to the most recently ended one.
    op.execute("""
        UPDATE store_session AS ss
        SET event_uuid = COALESCE(
            (
                SELECT e.uuid FROM event AS e
                WHERE e.end_time > ss.created
                ORDER BY e.end_time ASC
                LIMIT 1
            ),
            (
                SELECT e.uuid FROM event AS e
                ORDER BY e.end_time DESC
                LIMIT 1
            )
        )
    """)

    op.alter_column('store_session', 'event_uuid', existing_type=sa.UUID(), nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ticket_voucher_event_brand_uuid_event_brand'), 'ticket_voucher', type_='foreignkey')
    op.drop_column('ticket_voucher', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_ticket_type_event_brand_uuid_event_brand'), 'ticket_type', type_='foreignkey')
    op.drop_column('ticket_type', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_store_session_event_uuid_event'), 'store_session', type_='foreignkey')
    op.drop_column('store_session', 'event_uuid')
    op.drop_constraint(op.f('fk_seatmap_background_event_brand_uuid_event_brand'), 'seatmap_background', type_='foreignkey')
    op.drop_column('seatmap_background', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_seatmap_event_brand_uuid_event_brand'), 'seatmap', type_='foreignkey')
    op.drop_column('seatmap', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_position_event_brand_uuid_event_brand'), 'position', type_='foreignkey')
    op.drop_column('position', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_location_event_brand_uuid_event_brand'), 'location', type_='foreignkey')
    op.drop_column('location', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_event_event_brand_uuid_event_brand'), 'event', type_='foreignkey')
    op.drop_column('event', 'event_brand_uuid')
    op.drop_constraint(op.f('fk_crew_event_brand_uuid_event_brand'), 'crew', type_='foreignkey')
    op.drop_column('crew', 'event_brand_uuid')
    op.drop_table('event_brand')
    # ### end Alembic commands ###
